#!/usr/bin/env php
<?php
declare(strict_types = 1);

use OnceUponATime\Infrastructure\Common\OnceUponATimeApplicationContainer;

require_once __DIR__ . '/../vendor/autoload.php';

$container = new OnceUponATimeApplicationContainer();
$container->getConsoleApplication()->run();
